npm install express
npm install electron
npm install ws
npm install tailwindcss
npm install postcss
npm install autoprefixer
npm install mysql2
npm install passport
npm install passport-discord
npm install cookie-session